// @flow
// flow-typed signature: 60624e1ab8350736b048044bda023049
// flow-typed version: <<STUB>>/mobx-react_v5.3.6/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-react' {
  import type {ComponentType} from 'react'
  declare export function observer<P>(component:ComponentType<P>):ComponentType<P>
  // declare type Observer = <P>(component:ComponentType<P>) => ComponentType<P>
  // declare export type observer = Observer

}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx-react/__mocks__/react-native' {
  declare module.exports: any;
}

declare module 'mobx-react/custom' {
  declare module.exports: any;
}

declare module 'mobx-react/custom.module' {
  declare module.exports: any;
}

declare module 'mobx-react/empty' {
  declare module.exports: any;
}

declare module 'mobx-react/index.min' {
  declare module.exports: any;
}

declare module 'mobx-react/index.module' {
  declare module.exports: any;
}

declare module 'mobx-react/native' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobx-react/__mocks__/react-native.js' {
  declare module.exports: $Exports<'mobx-react/__mocks__/react-native'>;
}
declare module 'mobx-react/custom.js' {
  declare module.exports: $Exports<'mobx-react/custom'>;
}
declare module 'mobx-react/custom.module.js' {
  declare module.exports: $Exports<'mobx-react/custom.module'>;
}
declare module 'mobx-react/empty.js' {
  declare module.exports: $Exports<'mobx-react/empty'>;
}
declare module 'mobx-react/index' {
  declare module.exports: $Exports<'mobx-react'>;
}
declare module 'mobx-react/index.js' {
  declare module.exports: $Exports<'mobx-react'>;
}
declare module 'mobx-react/index.min.js' {
  declare module.exports: $Exports<'mobx-react/index.min'>;
}
declare module 'mobx-react/index.module.js' {
  declare module.exports: $Exports<'mobx-react/index.module'>;
}
declare module 'mobx-react/native.js' {
  declare module.exports: $Exports<'mobx-react/native'>;
}
